version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  colored:
    format: '%(asctime)s - %(name)s - %(levelname)-8s - %(message)s'
    datefmt: '%H:%M:%S'


handlers:
  # File Handler with rotate
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/cronjob.log
    maxBytes: 104857600  # 100MB
    backupCount: 5
    encoding: utf8
    mode: a

  # Console Handler
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  # File Handler Error
  error_file:
    class: logging.handler.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: logs/cronjob-error.log
    maxBytes: 10485760 # 10MB
    backupCount: 3
    encoding: utf8

loggers:
  # Logger for App
  cronjob:
    level: DEBUG
    handlers: [file, console, error_file]
    propagate: no

  # Logger for Scheduler
  schedule:
    level: WARNING
    handler: [file, console]

root:
  level: INFO
  handlers: [file, console, error_file]